/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmanclient;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Mark
 */
public class ClientFrame extends javax.swing.JFrame
{

static Client client;
static String answer;
int hintCounter = 2;
    /**
     * Creates new form ClientFrame
     */
    public ClientFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtGuessed = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnStartNewGame = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtWord = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        txtStep = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnHint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("IP: ");

        txtIP.setText("localhost");

        jLabel2.setText("Port: ");

        txtPort.setText("4444");

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jLabel3.setText("Input a letter or a word: ");

        txtGuessed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGuessedKeyPressed(evt);
            }
        });

        btnGuess.setText("Guess");
        btnGuess.setEnabled(false);
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnStartNewGame.setText("Start a new game");
        btnStartNewGame.setEnabled(false);
        btnStartNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartNewGameActionPerformed(evt);
            }
        });

        jLabel4.setText("Score: ");

        jLabel5.setText("Steps:");

        jLabel6.setText("The word: ");

        txtWord.setEditable(false);
        txtWord.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        txtScore.setEditable(false);
        txtScore.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        txtStep.setEditable(false);
        txtStep.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        btnHint.setText("Hint");
        btnHint.setEnabled(false);
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtStep, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtGuessed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHint)
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnStartNewGame))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnConnect))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnStartNewGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGuessed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHint))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt)                                           
    {                                               
 new Thread( new Runnable() {
            @Override
            public void run()
            {
                btnStartNewGame.setEnabled(true);
                txtScore.setText("0");

                String ip = txtIP.getText();
                int port = Integer.parseInt(txtPort.getText());

                client = new Client();
                client.ConnectServer(ip, port); // connect to the server

                btnConnect.setEnabled(false); }  }
).start();
    }                                          

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt)                                         
    {                                             
        // TODO add your handling code here:
        new Thread(new Runnable()
        {
            @Override
            public void run()
            {
                String guessed = txtGuessed.getText();
                String msg = client.SendGuess(guessed);
                String[] msgList = msg.split(",");
                switch (msgList[0])
                {
                    case "win":
                        txtWord.setText(msgList[1]);
                        txtScore.setText(msgList[2]);
                        btnGuess.setEnabled(false);
                        btnStartNewGame.setEnabled(true);
                        txtGuessed.setText("");
                        JOptionPane.showMessageDialog(btnConnect, "You win!\n The word is " + answer);
                        break;
                    case "loose":
                        txtScore.setText((Integer.parseInt(msgList[1])<0)?"0":msgList[1]);
                        btnGuess.setEnabled(false);
                        btnStartNewGame.setEnabled(true);
                        txtGuessed.setText("");
                        txtWord.setText("");
                        txtStep.setText("");
                        JOptionPane.showMessageDialog(btnConnect, "You loose!\n The word is " + answer);
                    case "uncompleted":
                        txtWord.setText(msgList[1]);
                        txtStep.setText(msgList[2]);
                        txtGuessed.setText("");
                        txtGuessed.getCursor();

                }

            }

        }).start();
    }                                        


    private void btnStartNewGameActionPerformed(java.awt.event.ActionEvent evt)                                                
    {                                                    
        // TODO add your handling code here:
     new Thread(new Runnable()
        {
            @Override
            public void run()
            {
                hintCounter = 2;
                btnGuess.setEnabled(true);
                btnHint.setEnabled(true);
                btnHint.setText("Hint ("+hintCounter+")");
                String temp[];
                String str;
                str = client.StartNewGame();
                temp = str.split(",");
                txtWord.setText(temp[1]);
                txtStep.setText(temp[2]);
                answer = temp[3];
                btnStartNewGame.setEnabled(false);
            }
        }).start();

    }                                               

    private void txtGuessedKeyPressed(java.awt.event.KeyEvent evt)                                      
    {                                          
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            new Thread(new Runnable()
            {

                @Override
                public void run()
                {

                    String guessed = txtGuessed.getText();
                    String msg = client.SendGuess(guessed);
                    String[] msgList = msg.split(",");
                    switch (msgList[0])
                    {
                        case "win":
                            txtWord.setText(msgList[1]);
                            txtScore.setText(msgList[2]);
                            btnGuess.setEnabled(false);
                            btnStartNewGame.setEnabled(true);
                            txtGuessed.setText("");
                            JOptionPane.showMessageDialog(btnConnect, "You win!\n The word is " + answer);
                            break;
                        case "loose":
                            txtScore.setText((Integer.parseInt(msgList[1])<0)?"0":msgList[1]);
                            btnGuess.setEnabled(false);
                            btnStartNewGame.setEnabled(true);
                            txtGuessed.setText("");
                            txtWord.setText("");
                            txtStep.setText("");
                            JOptionPane.showMessageDialog(btnConnect, "You loose!\n The word is " + answer);
                        case "uncompleted":
                            txtWord.setText(msgList[1]);
                        txtStep.setText(msgList[2]);
                            txtGuessed.setText("");
                            txtGuessed.getCursor();
                    }

                }

            }).start();
        }


    }                                     

    private void formWindowClosing(java.awt.event.WindowEvent evt)                                   
    {                                       
        // TODO add your handling code here:
        client.Disconnect();
    }                                  

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
        hintCounter--;
        btnHint.setText("Hint ("+hintCounter+")");
        String msg = client.getHint();
        System.out.println(msg);
        String[] msgList = msg.split(",");
        switch (msgList[0])
                    {
                        case "win":
                            txtWord.setText(msgList[1]);
                            txtScore.setText(msgList[2]);
                            btnGuess.setEnabled(false);
                            btnStartNewGame.setEnabled(true);
                            txtGuessed.setText("");
                            JOptionPane.showMessageDialog(btnConnect, "You win!\n The word is " + answer);
                            break;
                        case "loose":
                            txtScore.setText((Integer.parseInt(msgList[1])<0)?"0":msgList[1]);
                            btnGuess.setEnabled(false);
                            btnStartNewGame.setEnabled(true);
                            txtGuessed.setText("");
                            txtWord.setText("");
                            txtStep.setText("");
                            JOptionPane.showMessageDialog(btnConnect, "You loose!\n The word is " + answer);
                        case "uncompleted":
                            txtWord.setText(msgList[1]);
                        txtStep.setText(msgList[2]);
                            txtGuessed.setText("");
                            txtGuessed.getCursor();
                    }
        if(hintCounter == 0)
            btnHint.setEnabled(false);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
             
                ClientFrame cf = new ClientFrame();
                cf.setLocationRelativeTo(null);
                cf.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnHint;
    protected javax.swing.JButton btnStartNewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtGuessed;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtStep;
    private javax.swing.JTextField txtWord;
    // End of variables declaration                   
}

